### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6-UI#35]
**Describe the bug**
Default roles are not showing in the UI. 

**To Reproduce**
![image](https://user-images.githubusercontent.com/15981243/187396030-4ae9238c-14f7-4a29-8798-739e5119122a.png)

**Comment by frankcorneliusmartin** [comment]
Inspecting in the console showed this error: 

```
{"normalizedNames":{},"lazyUpdate":null},"status":500,"statusText":"INTERNAL SERVER ERROR","url":"https://petronas.vantage6.ai/role?organization_id=null&include_root=true","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://petronas.vantage6.ai/role?organization_id=null&include_root=true: 500 INTERNAL SERVER ERROR","error":{"msg":"An unexpected error occurred on the server!"}}
```

It seems to be related to the `null` value for the `organization_id`?

**Comment by bartvanb** [comment]
Just checked the server logs and found the following error:
```
2022-09-21T07:35:53.850352378Z Traceback (most recent call last):
2022-09-21T07:35:53.850358078Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
2022-09-21T07:35:53.850362778Z     cursor, statement, parameters, context
2022-09-21T07:35:53.850384078Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
2022-09-21T07:35:53.850388878Z     cursor.execute(statement, parameters)
2022-09-21T07:35:53.850392778Z psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "null"
2022-09-21T07:35:53.850396778Z LINE 4: WHERE role.organization_id IN ('null') OR role.organization_...
```
So indeed, it is related to the possible `null` value for `organization_id`.
The odd thing is that I don't have this problem locally. Currently I'm wondering if maybe SQLAlchemy doesn't properly translate the `None` [here](https://github.com/vantage6/vantage6/blob/main/vantage6-server/vantage6/server/resource/role.py#L233) for PostgreSQL (as it is working properly locally with SQLite)

**Comment by bartvanb** [comment]
Transfering this to the `vantage6` repo as it is a server issue
